# Generated by Django 6.0.3 on 2026-04-01 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tajenky', '0002_remove_tajenka_popis'),
    ]

    operations = [
        migrations.AddField(
            model_name='tajenka',
            name='source_url',
            field=models.URLField(blank=True, null=True, verbose_name='Zdrojová URL'),
        ),
    ]
